import {
  Card,
  Game,
  HeartBit,
  PersonSmall1,
  PersonSmall2,
  PersonSmall3,
  PersonSmall4,
  PersonSmall5,
  PersonSmall6,
  PersonSmall7,
  Sber,
  SBP,
  Trend,
} from "@/icons";
import { FunctionComponent, SVGProps } from "react";

export interface ITableCotent {
  personName: string;
  personIcon: FunctionComponent<SVGProps<SVGSVGElement>>;
  amount: string;
  margin: number;
  comment: string;
  source: string;
  sourceIcon: FunctionComponent<SVGProps<SVGSVGElement>>;
  sourceColor: string;
  sourceTextColor: string;
  paymentMethod: string;
  paymentMethodIcon: FunctionComponent<SVGProps<SVGSVGElement>>;
  _isNew?: boolean;
}
export const tableContent: ITableCotent[] = [
  {
    personName: "Gusein Gasanov",
    personIcon: PersonSmall1,
    amount: "500 RUB",
    margin: 100,
    comment: "Got Paid ₽500",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Alexander Bare",
    personIcon: PersonSmall2,
    amount: "700 USD",
    margin: 70,
    comment: "₽11,000 to $133",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Johnatan Davids",
    personIcon: PersonSmall3,
    amount: "5500 AZN",
    margin: -50,
    comment: "Received $125",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Vivian Monclair",
    personIcon: PersonSmall4,
    amount: "8200 RUB",
    margin: 20,
    comment: "Got Paid ₽8200",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ekaterina Ivanova",
    personIcon: PersonSmall5,
    amount: "5500 AZN",
    margin: -50,
    comment: "Received $90",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "John Malkovich",
    personIcon: PersonSmall6,
    amount: "3000 RUB",
    margin: 200,
    comment: "Got Paid ₽3000",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Almaz Abdulov",
    personIcon: PersonSmall7,
    amount: "700 USD",
    margin: 55,
    comment: "₽22,000 to $245",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Josh Enkolt",
    personIcon: PersonSmall1,
    amount: "400 EUR",
    margin: 100,
    comment: "Got Paid $423",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Timur Mudiskiy",
    personIcon: PersonSmall3,
    amount: "7750 AZN",
    margin: -20,
    comment: "Received $188",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Mila Alientes",
    personIcon: PersonSmall2,
    amount: "350 USD",
    margin: 70,
    comment: "₽5,500 to $68",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Vitort Moldur",
    personIcon: PersonSmall4,
    amount: "8200 RUB",
    margin: 20,
    comment: "Got Paid ₽8200",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ann Kamarenko",
    personIcon: PersonSmall5,
    amount: "11,000 AZN",
    margin: -100,
    comment: "Received $180",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Pavel Matskevich",
    personIcon: PersonSmall6,
    amount: "3000 RUB",
    margin: 200,
    comment: "Got Paid ₽3000",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ali Matr",
    personIcon: PersonSmall7,
    amount: "350 USD",
    margin: 55,
    comment: "₽11,000 to $123",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
];

export const MAX_VISIBLE = 7;
export const ROW_HEIGHT = 50;
export const INTERVAL = 7000;
export const ANIM_DURATION = 500;
export const HIGHLIGHT_DURATION = 750;
