import {
  Card,
  Game,
  HeartBit,
  PersonSmall1,
  PersonSmall2,
  PersonSmall3,
  PersonSmall4,
  PersonSmall5,
  PersonSmall6,
  PersonSmall7,
  Sber,
  SBP,
  Trend,
} from "@/icons";
import { FunctionComponent, SVGProps } from "react";

export interface ITableCotent {
  personName: string;
  personIcon: string;
  amount: number;
  currency: string;
  margin: number;
  comment: string;
  source: string;
  sourceIcon: FunctionComponent<SVGProps<SVGSVGElement>>;
  sourceColor: string;
  sourceTextColor: string;
  paymentMethod: string;
  paymentMethodIcon: FunctionComponent<SVGProps<SVGSVGElement>>;
  _isNew?: boolean;
}
export const tableContent: ITableCotent[] = [
  {
    personName: "Gusein Gasanov",
    personIcon: PersonSmall1,
    amount: 5000,
    currency: "RUB",
    margin: 10,
    comment: "Got Paid 500 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Alexander Bare",
    personIcon: PersonSmall2,
    amount: 7000,
    currency: "RUB",
    margin: 7,
    comment: "Got Paid 490 RUB",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Johnatan Davids",
    personIcon: PersonSmall3,
    amount: 55000,
    currency: "AZN",
    margin: 5,
    comment: "Got Paid 125 USD",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Vivian Monclair",
    personIcon: PersonSmall4,
    amount: 8200,
    currency: "RUB",
    margin: 2,
    comment: "Got Paid 164 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ekaterina Ivanova",
    personIcon: PersonSmall5,
    amount: 5500,
    currency: "AZN",
    margin: 5,
    comment: "Got Paid 90 USD",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "John Malkovich",
    personIcon: PersonSmall6,
    amount: 30000,
    currency: "RUB",
    margin: 10,
    comment: "Got Paid 3000 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Almaz Abdulov",
    personIcon: PersonSmall7,
    amount: 700,
    currency: "USD",
    margin: 5.5,
    comment: "Got Paid 39 USD",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Josh Enkolt",
    personIcon: PersonSmall1,
    amount: 4000,
    currency: "RUB",
    margin: 10.5,
    comment: "Got Paid 420 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Timur Mudiskiy",
    personIcon: PersonSmall3,
    amount: 7750,
    currency: "AZN",
    margin: 2,
    comment: "Got Paid 188 USD",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Mila Alientes",
    personIcon: PersonSmall2,
    amount: 3500,
    currency: "USD",
    margin: 7,
    comment: "Got Paid 24.5 USD",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
  {
    personName: "Vitort Moldur",
    personIcon: PersonSmall4,
    amount: 8200,
    currency: "RUB",
    margin: 2,
    comment: "Got Paid 8200 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ann Kamarenko",
    personIcon: PersonSmall5,
    amount: 11000,
    currency: "AZN",
    margin: 10,
    comment: "Got Paid 180 USD",
    source: "Gamebet",
    sourceIcon: Game,
    sourceTextColor: "#A808C8",
    sourceColor: "#FBE8FF",
    paymentMethod: "SBP",
    paymentMethodIcon: SBP,
  },
  {
    personName: "Pavel Matskevich",
    personIcon: PersonSmall6,
    amount: 30000,
    currency: "RUB",
    margin: 10,
    comment: "Got Paid 3000 RUB",
    source: "Forex",
    sourceIcon: Trend,
    sourceTextColor: "#3083FF",
    sourceColor: "#EDF5FE",
    paymentMethod: "SberPay",
    paymentMethodIcon: Sber,
  },
  {
    personName: "Ali Matr",
    personIcon: PersonSmall7,
    amount: 350,
    currency: "USD",
    margin: 5.5,
    comment: "Got Paid 176 USD",
    source: "Adult",
    sourceIcon: HeartBit,
    sourceTextColor: "#FF5151",
    sourceColor: "#FFE6E6",
    paymentMethod: "Card",
    paymentMethodIcon: Card,
  },
];

export const MAX_VISIBLE = 7;
export const ROW_HEIGHT = 50;
export const MOBILE_MULTIPLYER = 3.5;
export const INTERVAL = 7000;
export const ANIM_DURATION = 500;
export const HIGHLIGHT_DURATION = 750;
